services:
  django:
    build:
      context: ./django_app
      dockerfile: Dockerfile.prod
    container_name: porfolio_django_prod
    volumes:
      - static_volume:/app/staticfiles
      - ./data:/app/data
      - ./logs:/app/logs
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - fastapi
    restart: unless-stopped

  
  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile.prod
    container_name: porfolio_fastapi_prod
    expose:
      - "8001"
    env_file:
      - .env.prod
    restart: unless-stopped


  nginx:
    build: ./nginx
    container_name: portfolio_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/www/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
      - fastapi
    restart: unless-stopped


volumes:
  static_volume:
